Update deploy.yml
fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -46,6 +46,10 @@ jobs:
         script: |
           cd /home/bekzhan/backend
           rm -f Affaci-0.0.1-SNAPSHOT.jar
-          scp target/Affaci-0.0.1-SNAPSHOT.jar root@${{ secrets.SERVER_IP }}:/home/bekzhan/backend/
+          scp -o StrictHostKeyChecking=no target/Affaci-0.0.1-SNAPSHOT.jar root@${{ secrets.SERVER_IP }}:/home/bekzhan/backend/
+          if [ $? -ne 0 ]; then
+            echo "SCP failed"
+            exit 1
+          fi
           sudo systemctl restart backend.service
 
